---

- name: Add nginx group
  group:
    name: nginx
    state: present


- name: Add nginx
  user:
    name: nginx
    group: nginx
    createhome: no
    shell: /sbin/nologin
   

- name: Install depend package
  yum:
    name: "{{ item }}"
    state: present

  loop:
    - gcc
    - openssl-devel
    - pcre-devel

- name: Unzip nginx.tar.gz
  unarchive:
    src: "{{ tarball_name }}"
    dest: /usr/local/src


- name: Configure
  command:   ./configure --user=nginx --group=nginx   --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module
  args:
    chdir: /usr/local/src/{{ nginx_dir }}


- name: Make
  command: make
  args:
    chdir: /usr/local/src/{{ nginx_dir }}


- name: Make  install
  command: make install
  args:
    chdir: /usr/local/src/{{ nginx_dir }}

- name: Create nginx script for centos6
  copy: 
    src: nginx_centos6.sh
    dest: /etc/init.d/nginx
    mode: 755
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")


- name: Create nginx script for cenots7
  copy:
    src: nginx_centos7.sh
    dest: /usr/lib/systemd/system/nginx.service
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  notify:
    - Reload service

- meta: flush_handlers


#- name: Add nginx to start menu
#  service:
#    name: nginx
#    enabled: yes
#    state: started


- name: Modify nginx configuration
  copy:
    src: nginx.conf
    dest: /usr/local/nginx/conf/nginx.conf
  notify: Restart nginx


- name: Create nginx vhost dir
  file:
    path: /usr/local/nginx/conf/extra
    state: directory


- name: Wordpress nginx conf
  template:
    src: wordpress.conf.j2
    dest: /usr/local/nginx/conf/extra/wordpress.conf 
  notify: Restart nginx

