---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress
  remote_user: root
  # remote_user: user
  # become: yes
  # become_method: sudo

  roles:
    - role: common
    - role: mysql
      tags: ["mysql"]
    - role: nginx
      tags: ["nginx"]
    - role: php-fpm
      tags: ["php-fpm"]
    - role: wordpress
      tags: ["wordpress"]
